export const FETCH_TICKETS = "FETCH_TICKETS";
export const FETCH_TICKETS_SUCCESS = "FETCH_TICKETS_SUCCESS";
export const FETCH_TICKETS_FAILE = "FETCH_TICKETS_FAILE";
export const FETCH_TICKETS_LOADING = "FETCH_TICKETS_LOADING";
